# Generated by Django 4.2.30 on 2026-07-15 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variance_weight', models.FloatField(default=0.6)),
                ('conflict_penalty_weight', models.FloatField(default=0.4)),
                ('protected_slot_penalty', models.FloatField(default=8.0)),
                ('population_size', models.IntegerField(default=200)),
                ('max_generations', models.IntegerField(default=500)),
                ('mutation_rate', models.FloatField(default=0.05)),
                ('crossover_rate', models.FloatField(default=0.85)),
                ('timeout_seconds', models.IntegerField(default=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'algorithm_config',
            },
        ),
    ]
