# Generated by Django 4.2.30 on 2026-07-15 08:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_course_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20)),
                ('course_count', models.IntegerField(default=0)),
                ('conflict_pairs_count', models.IntegerField(default=0)),
                ('threshold', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'conflict_analysis_result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConflictTaskRecord',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', '等待中'), ('RUNNING', '执行中'), ('SUCCESS', '完成'), ('FAILED', '失败')], default='PENDING', max_length=10)),
                ('progress', models.FloatField(default=0.0)),
                ('analyzed_pairs', models.IntegerField(default=0)),
                ('total_pairs', models.IntegerField(default=0)),
                ('conflict_pairs_found', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conflict_analysis.conflictanalysisresult')),
            ],
            options={
                'db_table': 'conflict_task_record',
            },
        ),
        migrations.CreateModel(
            name='ConflictPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflicting_student_count', models.IntegerField(default=0)),
                ('conflict_rate', models.FloatField(default=0.0)),
                ('course_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_a', to='courses.course')),
                ('course_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_b', to='courses.course')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='conflict_analysis.conflictanalysisresult')),
            ],
            options={
                'db_table': 'conflict_pair',
                'ordering': ['-conflicting_student_count'],
            },
        ),
    ]
