# Generated by Django 4.2.30 on 2026-07-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('MANAGER', '管理员'), ('ADMIN', '教务'), ('TEACHER', '教师'), ('STUDENT', '学生')], default='STUDENT', max_length=10),
        ),
    ]
