# Generated by Django 4.2.30 on 2026-07-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_session_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="session_length",
            field=models.IntegerField(
                default=2, help_text="每次课连排节数（每门课程独立设置）"
            ),
        ),
    ]
