// CourseQSort Admin UI Controller
(function() {
    // 预览模式下跳过认证检查，后端模式才需要登录
    if (!CourseQSortAPI.isMockMode() && !CourseQSortAPI.isAuthenticated()) { window.location.href = 'login.html'; return; }
    document.getElementById('admin-mode-badge').textContent = CourseQSortAPI.isMockMode() ? '预览模式' : '后端模式';
})();
var W = ['','周一','周二','周三','周四','周五'];
var P = ['','第1节','第2节','第3节','第4节','第5节','第6节','第7节','第8节','第9节','第10节','第11节'];
var curSec = 'dashboard';
document.querySelectorAll('#admin-nav a[data-section]').forEach(function(l){l.addEventListener('click',function(e){e.preventDefault();switchSec(this.getAttribute('data-section'));});});
document.getElementById('admin-logout-btn').addEventListener('click',function(e){e.preventDefault();CourseQSortAPI.token.clear();sessionStorage.clear();window.location.href='login.html';});
function switchSec(s){curSec=s;document.querySelectorAll('#admin-nav a[data-section]').forEach(function(l){l.classList.remove('active');});document.querySelector('#admin-nav a[data-section="'+s+'"]').classList.add('active');document.querySelectorAll('.admin-section').forEach(function(s){s.classList.add('d-none');});var el=document.getElementById('section-'+s);if(el)el.classList.remove('d-none');if(s==='dashboard')loadDash();else if(s==='courses')loadCourses();else if(s==='resources')loadRes();else if(s==='protected-slots')loadSlots();else if(s==='scheduling')loadPlans();else if(s==='conflict')loadConflict();else if(s==='algorithm')loadAlgo();}
async function loadDash(){try{var c=await CourseQSortAPI.admin.getCourses();var t=await CourseQSortAPI.admin.getTeachers();var r=await CourseQSortAPI.admin.getClassrooms();var m=await CourseQSortAPI.admin.getMajors();document.getElementById('dashboard-cards').innerHTML='<div class="col-md-3"><div class="card text-bg-primary"><div class="card-body text-center"><h3>'+(c.count||0)+'</h3><small>课程总数</small></div></div></div><div class="col-md-3"><div class="card text-bg-success"><div class="card-body text-center"><h3>'+(t.count||0)+'</h3><small>教师数</small></div></div></div><div class="col-md-3"><div class="card text-bg-info"><div class="card-body text-center"><h3>'+(r.count||0)+'</h3><small>教室数</small></div></div></div><div class="col-md-3"><div class="card text-bg-warning"><div class="card-body text-center"><h3>'+(m.count||0)+'</h3><small>专业数</small></div></div></div>';document.getElementById('dashboard-hint').textContent='数据来源: '+(CourseQSortAPI.isMockMode()?'本地模拟数据':'后端服务器');}catch(e){document.getElementById('dashboard-cards').innerHTML='<div class="col-12 text-danger">加载失败</div>';}}
var courseData=[],courseSearch='';async function loadCourses(){try{var d=await CourseQSortAPI.admin.getCourses();courseData=d.results||[];renderCourses();}catch(e){document.getElementById('admin-course-list').innerHTML='<tr><td colspan="8" class="text-danger">加载失败</td></tr>';}}
function renderCourses(){var q=(document.getElementById('course-search').value||'').toLowerCase();var f=courseData;if(q)f=courseData.filter(function(c){return(c.name||'').toLowerCase().indexOf(q)!==-1||(c.code||'').toLowerCase().indexOf(q)!==-1;});document.getElementById('admin-course-list').innerHTML=f.map(function(c){var tn=(c.teachers||[]).map(function(t){return t.name;}).join(', ');return'<tr><td>'+c.name+'</td><td>'+(c.code||'-')+'</td><td>'+c.credit+'</td><td>'+tn+'</td><td>'+(c.major?c.major.name:'-')+'</td><td>'+(c.expected_student_count||'-')+'</td><td>'+(c.is_professional_course?'专业':'通识')+'</td><td><button class="btn btn-outline-primary btn-sm py-0">编辑</button></td></tr>';}).join('')||'<tr><td colspan="8" class="text-muted">暂无数据</td></tr>';}
document.getElementById('course-search').addEventListener('input',renderCourses);
document.getElementById('course-add-btn').addEventListener('click',function(){document.getElementById('course-modal-title').textContent='新增课程';document.getElementById('course-modal-body').innerHTML='<div class="mb-2"><label class="form-label">课程名称</label><input class="form-control form-control-sm" id="c-name"></div><div class="mb-2"><label class="form-label">编号</label><input class="form-control form-control-sm" id="c-code"></div><div class="mb-2"><label class="form-label">学分</label><input type="number" class="form-control form-control-sm" id="c-credit" value="3"></div><div class="mb-2"><label class="form-label">容量</label><input type="number" class="form-control form-control-sm" id="c-capacity" value="100"></div>';new bootstrap.Modal(document.getElementById('course-modal')).show();});
document.getElementById('course-modal-save').addEventListener('click',function(){alert('课程保存成功（模拟）');bootstrap.Modal.getInstance(document.getElementById('course-modal')).hide();loadCourses();});
document.getElementById('course-import-btn').addEventListener('click',function(){alert('导入功能：请上传 Excel 文件（模拟）');});
var curRes='teachers';document.querySelectorAll('#resource-tabs a').forEach(function(t){t.addEventListener('click',function(e){e.preventDefault();document.querySelectorAll('#resource-tabs a').forEach(function(x){x.classList.remove('active');});this.classList.add('active');curRes=this.getAttribute('data-resource');loadResTable();});});
async function loadRes(){await loadResTable();}
async function loadResTable(){var tb=document.getElementById('resource-table-body');try{if(curRes==='teachers'){var d=await CourseQSortAPI.admin.getTeachers();var items=d.results||[];tb.innerHTML='<tr><th>姓名</th><th>工号</th><th>学院</th><th>禁排时段</th></tr>'+items.map(function(t){var s=(t.unavailable_slots||[]).map(function(s){return'周'+['','一','二','三','四','五'][s.day_of_week]+'第'+s.period+'节';}).join(', ')||'无';return'<tr><td>'+t.name+'</td><td>'+(t.employee_no||'-')+'</td><td>'+(t.department||'-')+'</td><td class="small">'+s+'</td></tr>';}).join('');}else if(curRes==='classrooms'){var d=await CourseQSortAPI.admin.getClassrooms();var items=d.results||[];tb.innerHTML='<tr><th>名称</th><th>容量</th><th>楼宇</th><th>设备</th><th>类型</th></tr>'+items.map(function(r){return'<tr><td>'+r.name+'</td><td>'+r.capacity+'</td><td>'+(r.building||'-')+'</td><td class="small">'+(r.equipment_types||[]).join(', ')+'</td><td>'+(r.is_lab?'实验室':'普通')+'</td></tr>';}).join('');}else{var d=await CourseQSortAPI.admin.getMajors();var items=d.results||[];tb.innerHTML='<tr><th>名称</th><th>编号</th><th>学生数</th></tr>'+items.map(function(m){return'<tr><td>'+m.name+'</td><td>'+(m.code||'-')+'</td><td>'+(m.student_count||0)+'</td></tr>';}).join('');}}catch(e){tb.innerHTML='<tr><td colspan="4" class="text-danger">加载失败</td></tr>';}}
async function loadSlots(){try{var d=await CourseQSortAPI.admin.getProtectedSlots();var slots=d.results||[];var tb=document.getElementById('protected-slots-list');tb.innerHTML=slots.map(function(s){return'<tr><td>'+W[s.day_of_week]+'</td><td>'+P[s.start_period]+' ~ '+P[s.end_period]+'</td><td>'+s.penalty_weight+'</td><td>'+s.description+'</td><td><button class="btn btn-outline-danger btn-sm py-0 del-slot" data-id="'+s.id+'">删除</button></td></tr>';}).join('')||'<tr><td colspan="5" class="text-muted">暂无保护时段</td></tr>';document.querySelectorAll('.del-slot').forEach(function(b){b.addEventListener('click',async function(){var id=parseInt(this.getAttribute('data-id'));await CourseQSortAPI.admin.deleteProtectedSlot(id);loadSlots();});});}catch(e){}}
document.getElementById('protected-add-btn').addEventListener('click',function(){document.getElementById('slot-modal-body').innerHTML='<div class="mb-2"><label class="form-label">星期</label><select class="form-select form-select-sm" id="s-day">'+[1,2,3,4,5].map(function(d){return'<option value="'+d+'">'+W[d]+'</option>';}).join('')+'</select></div><div class="mb-2"><label class="form-label">起始节次</label><select class="form-select form-select-sm" id="s-start">'+[1,2,3,4,5,6,7,8,9,10,11].map(function(p){return'<option value="'+p+'">'+P[p]+'</option>';}).join('')+'</select></div><div class="mb-2"><label class="form-label">结束节次</label><select class="form-select form-select-sm" id="s-end">'+[1,2,3,4,5,6,7,8,9,10,11].map(function(p){return'<option value="'+p+'">'+P[p]+'</option>';}).join('')+'</select></div><div class="mb-2"><label class="form-label">惩罚权重(0~10)</label><input type="range" class="form-range" id="s-weight" min="0" max="10" step="0.5" value="8"><span id="s-weight-val">8.0</span></div><div class="mb-2"><label class="form-label">说明</label><input class="form-control form-control-sm" id="s-desc" placeholder="辅修热门时段"></div>';document.getElementById('s-weight').addEventListener('input',function(){document.getElementById('s-weight-val').textContent=parseFloat(this.value).toFixed(1);});new bootstrap.Modal(document.getElementById('slot-modal')).show();});
document.getElementById('slot-modal-save').addEventListener('click',async function(){var data={day_of_week:parseInt(document.getElementById('s-day').value),start_period:parseInt(document.getElementById('s-start').value),end_period:parseInt(document.getElementById('s-end').value),penalty_weight:parseFloat(document.getElementById('s-weight').value),description:document.getElementById('s-desc').value||''};await CourseQSortAPI.admin.addProtectedSlot(data);bootstrap.Modal.getInstance(document.getElementById('slot-modal')).hide();loadSlots();});
document.getElementById('protected-batch-btn').addEventListener('click',function(){alert('批量更新：将替换所有保护时段（模拟）');});
async function loadPlans(){try{var d=await CourseQSortAPI.admin.getSchedulePlans();var plans=d.results||[];var tb=document.getElementById('schedule-plans-list');var SM={DRAFT:'草稿',PUBLISHED:'已发布',GENERATING:'生成中'};tb.innerHTML=plans.map(function(p){var eb='<button class="btn btn-outline-info btn-sm py-0 eval-plan" data-id="'+p.id+'">评估</button>';var pb=p.status==='DRAFT'?' <button class="btn btn-outline-success btn-sm py-0 pub-plan" data-id="'+p.id+'">发布</button>':'';return'<tr><td>'+p.plan_name+'</td><td>'+p.semester+'</td><td><span class="badge bg-'+(p.status==='PUBLISHED'?'success':'secondary')+'">'+(SM[p.status]||p.status)+'</span></td><td>'+(p.overall_fitness!=null?p.overall_fitness:'-')+'</td><td class="small">'+(p.created_at?p.created_at.replace('T',' ').slice(0,16):'-')+'</td><td>'+eb+pb+'</td></tr>';}).join('')||'<tr><td colspan="6" class="text-muted">暂无方案</td></tr>';document.querySelectorAll('.eval-plan').forEach(function(b){b.addEventListener('click',async function(){var id=parseInt(this.getAttribute('data-id'));try{var e=await CourseQSortAPI.admin.getSchedulePlanEvaluation(id);alert('方案评估:\n总体适应度: '+e.overall_fitness+'\n课时方差: '+e.daily_hour_variance+'\n每日分布: '+(e.daily_distribution||[]).join(', ')+'\n保护时段占用: '+e.protected_slot_occupied);}catch(ex){alert('加载评估失败');}});});document.querySelectorAll('.pub-plan').forEach(function(b){b.addEventListener('click',async function(){var id=parseInt(this.getAttribute('data-id'));await CourseQSortAPI.admin.publishPlan(id);loadPlans();});});}catch(e){}}
document.getElementById('schedule-generate-btn').addEventListener('click',async function(){var el=document.getElementById('schedule-task-status');el.className='alert alert-info';el.textContent='正在生成排课方案...';try{var r=await CourseQSortAPI.admin.generateSchedule({plan_name:'新方案-'+new Date().toLocaleString(),semester:'2026-spring',major_ids:[1,2,3],algorithm_config:{}});el.className='alert alert-success';el.textContent='生成任务已提交，模拟执行中...';setTimeout(function(){el.textContent='方案生成完成！';loadPlans();},2000);}catch(e){el.className='alert alert-danger';el.textContent='生成失败';}});
async function loadConflict(){try{var d=await CourseQSortAPI.admin.getConflictResults();var rs=d.results||[];var tb=document.getElementById('conflict-results-list');tb.innerHTML=rs.map(function(r){return'<tr><td>'+r.id+'</td><td>'+r.semester+'</td><td>'+r.course_count+'</td><td>'+r.conflict_pairs_count+'</td><td>'+r.threshold+'</td><td class="small">'+(r.created_at?r.created_at.replace('T',' ').slice(0,16):'-')+'</td><td><button class="btn btn-outline-danger btn-sm py-0 view-pairs" data-id="'+r.id+'">查看冲突对</button></td></tr>';}).join('')||'<tr><td colspan="7" class="text-muted">暂无结果</td></tr>';document.querySelectorAll('.view-pairs').forEach(function(b){b.addEventListener('click',async function(){var id=parseInt(this.getAttribute('data-id'));try{var pd=await CourseQSortAPI.admin.getConflictPairs(id);var pairs=pd.results||[];var area=document.getElementById('conflict-chart-area');area.innerHTML='<h6>冲突课程对</h6>'+pairs.map(function(p){var h=Math.min(100,(p.conflicting_student_count/60)*100);return'<div class="mb-1 d-flex align-items-center"><div style="flex:1;font-size:12px;">'+p.course_a.name+' vs '+p.course_b.name+'</div><div class="me-2 text-end" style="width:30px;font-size:12px;">'+p.conflicting_student_count+'</div><div style="height:20px;width:'+h+'%;background:#dc3545;border-radius:3px;min-width:4px;"></div></div>';}).join('');}catch(ex){alert('加载失败');}});});}catch(e){}}
document.getElementById('conflict-run-btn').addEventListener('click',async function(){var el=document.getElementById('conflict-task-status');el.className='alert alert-warning';el.textContent='正在运行冲突分析...';try{var r=await CourseQSortAPI.admin.runConflictAnalysis({semester:'2026-spring',course_ids:[],threshold:30});el.className='alert alert-success';el.textContent='分析任务已提交';setTimeout(function(){el.textContent='分析完成！共发现 15 对冲突课程';loadConflict();},1500);}catch(e){el.className='alert alert-danger';el.textContent='分析失败';}});
async function loadAlgo(){try{var c=await CourseQSortAPI.admin.getAlgorithmConfig();var form=document.getElementById('algorithm-config-form');form.innerHTML='';var ps=[{k:'variance_weight',l:'均衡度权重',min:0,max:1,st:0.1,d:'越大越注重均衡'},{k:'conflict_penalty_weight',l:'冲突惩罚权重',min:0,max:1,st:0.1,d:'与均衡度权重之和为1'},{k:'protected_slot_penalty',l:'辅修时段惩罚',min:0,max:10,st:0.5,d:'越大越避免占用'},{k:'population_size',l:'种群大小',min:50,max:500,st:10,d:'遗传算法种群规模'},{k:'max_generations',l:'最大迭代代数',min:100,max:2000,st:50,d:'算法运行代数'},{k:'mutation_rate',l:'变异率',min:0,max:0.2,st:0.01,d:'变异概率'},{k:'crossover_rate',l:'交叉率',min:0.5,max:1,st:0.05,d:'交叉概率'},{k:'timeout_seconds',l:'超时时间(秒)',min:60,max:600,st:10,d:'算法超时限制'}];ps.forEach(function(p){var v=c[p.k]!=null?c[p.k]:p.min;form.innerHTML+='<div class="col-md-6"><div class="card"><div class="card-body py-2"><label class="form-label small">'+p.l+' <span class="badge bg-secondary" id="ap-'+p.k+'">'+v+'</span></label><input type="range" class="form-range" id="a-'+p.k+'" min="'+p.min+'" max="'+p.max+'" step="'+p.st+'" value="'+v+'"><small class="text-muted">'+p.d+'</small></div></div></div>';});ps.forEach(function(p){var el=document.getElementById('a-'+p.k);if(el){el.addEventListener('input',function(){document.getElementById('ap-'+p.k).textContent=parseFloat(this.value);});}});}catch(e){}}
document.getElementById('algorithm-save-btn').addEventListener('click',async function(){var cfg={};['variance_weight','conflict_penalty_weight','protected_slot_penalty','population_size','max_generations','mutation_rate','crossover_rate','timeout_seconds'].forEach(function(k){var el=document.getElementById('a-'+k);if(el)cfg[k]=parseFloat(el.value);});try{await CourseQSortAPI.admin.updateAlgorithmConfig(cfg);document.getElementById('algorithm-save-status').textContent='配置已保存';document.getElementById('algorithm-save-status').className='mt-2 small text-success';}catch(e){document.getElementById('algorithm-save-status').textContent='保存失败';document.getElementById('algorithm-save-status').className='mt-2 small text-danger';}});
switchSec('dashboard');
