# Generated by Django 4.2.30 on 2026-07-15 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_course_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=200)),
                ('semester', models.CharField(blank=True, default='', max_length=20)),
                ('major_ids', models.JSONField(blank=True, default=list)),
                ('overall_fitness', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PUBLISHED', '已发布')], default='DRAFT', max_length=10)),
                ('algorithm_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'schedule_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskRecord',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', '等待中'), ('RUNNING', '执行中'), ('SUCCESS', '完成'), ('FAILED', '失败')], default='PENDING', max_length=10)),
                ('progress', models.FloatField(default=0.0)),
                ('current_generation', models.IntegerField(blank=True, null=True)),
                ('best_fitness', models.FloatField(blank=True, null=True)),
                ('estimated_time_remaining', models.CharField(blank=True, default='', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.scheduleplan')),
            ],
            options={
                'db_table': 'task_record',
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField()),
                ('period', models.IntegerField()),
                ('student_group_ids', models.JSONField(blank=True, default=list)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.classroom')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='scheduling.scheduleplan')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.teacher')),
            ],
            options={
                'db_table': 'schedule_entry',
                'ordering': ['day_of_week', 'period'],
            },
        ),
    ]
