# Generated by Django 4.2.30 on 2026-07-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField()),
                ('start_period', models.IntegerField()),
                ('end_period', models.IntegerField()),
                ('penalty_weight', models.FloatField(default=8.0)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'db_table': 'protected_slot',
                'ordering': ['day_of_week', 'start_period'],
            },
        ),
    ]
